language: objective-c
osx_image: xcode11.6

cache:
  - bundler
  - cocoapods

before_install:
  - bundle install # --deployment # to cache vendor/bundle
  - bundle exec pod install --repo-update

script:
  - set -o pipefail && xcodebuild -workspace LayoutFrameworkBenchmark.xcworkspace -scheme LayoutFrameworkBenchmark -sdk iphonesimulator13.6 -destination 'platform=iOS Simulator,name=iPhone 8' build | xcpretty
