language: objective-c
osx_image: xcode10.0

before_install:
  - gem install xcpretty-travis-formatter;
  - gem install cocoapods --no-document --quiet;
  - pod install --repo-update;

script:
  - set -o pipefail && xcodebuild -workspace LayoutFrameworkBenchmark.xcworkspace -scheme LayoutFrameworkBenchmark -sdk iphonesimulator12.0 -destination 'platform=iOS Simulator,name=iPhone 8' build | xcpretty -f `xcpretty-travis-formatter`
