language: objective-c
osx_image: xcode12

cache:
  - bundler
  - cocoapods

before_install:
  - bundle install # --deployment # to cache vendor/bundle
  - pod install --repo-update;

script:
  - set -o pipefail && xcodebuild -workspace LayoutFrameworkBenchmark.xcworkspace -scheme LayoutFrameworkBenchmark -sdk iphonesimulator12.0 -destination 'platform=iOS Simulator,name=iPhone 8' build | xcpretty -f `xcpretty-travis-formatter`
